//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ApplicationLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ApplicationLog()
        {
            this.T_ApplicationLog1 = new HashSet<T_ApplicationLog>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateTime { get; set; }
        public byte Types { get; set; }
        public Nullable<System.Guid> FK_Parent_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ApplicationLog> T_ApplicationLog1 { get; set; }
        public virtual T_ApplicationLog T_ApplicationLog2 { get; set; }
        public virtual T_ApplicationLog_Exception T_ApplicationLog_Exception { get; set; }
    }
}
