//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordBill.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecordBillDBEntities : DbContext
    {
        public RecordBillDBEntities()
            : base("name=RecordBillDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Bill> T_Bill { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_ApplicationLog> T_ApplicationLog { get; set; }
        public virtual DbSet<T_ApplicationLog_Exception> T_ApplicationLog_Exception { get; set; }
        public virtual DbSet<V_ApplicationLog_Exception> V_ApplicationLog_Exception { get; set; }
        public virtual DbSet<T_Token> T_Token { get; set; }
        public virtual DbSet<V_Token> V_Token { get; set; }
        public virtual DbSet<V_User> V_User { get; set; }
    }
}
