//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ApplicationLog_Exception
    {
        public System.Guid FK_Log_ID { get; set; }
        public string StackTrace { get; set; }
        public string Types { get; set; }
    
        public virtual T_ApplicationLog T_ApplicationLog { get; set; }
    }
}
