//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bill
    {
        public System.Guid ID { get; set; }
        public System.Guid FK_User_ID { get; set; }
        public string Contents { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime RecordTime { get; set; }
        public System.DateTimeOffset CreateTime { get; set; }
        public System.Guid FK_Type_ID { get; set; }
    
        public virtual T_BillTypes T_BillTypes { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
