//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordBill.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ApplicationLog_Exception
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string Types { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.Guid> FK_Parent_ID { get; set; }
    }
}
